# Generated by Django 5.1.7 on 2025-03-29 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustentabilidade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosustentavel',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariosustentavel',
            name='consumo_agua',
            field=models.FloatField(help_text='Consumo de água em L/dia'),
        ),
        migrations.AlterField(
            model_name='usuariosustentavel',
            name='consumo_energia',
            field=models.FloatField(help_text='Consumo de energia em kWh/dia'),
        ),
        migrations.AlterField(
            model_name='usuariosustentavel',
            name='residuos',
            field=models.FloatField(help_text='Resíduos não recicláveis em kg/dia'),
        ),
        migrations.AlterField(
            model_name='usuariosustentavel',
            name='uso_transporte',
            field=models.FloatField(help_text='Distância percorrida em km/dia'),
        ),
    ]
